version: "3"
services:
  frontend:
    image: frontend
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  database:
    image: database
    ports:
      - "3307:3306"
    networks:
      - webnet
  api:
    image: api
    environment:
      - DB_HOST=172.17.0.1
      - DB_PORT=3307
      - DB_USER=docker_user
      - DB_PASSWORD=123456
      - DB_DATABASE=crud_simples
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet: