version: "3"
services:
  frontend:
    image: frontend
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  database:
    image: database
    ports:
      - "3307:3306"
    networks:
      - webnet
  api:
    image: api
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet: